apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-kibana
  name: elasticsearch-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch-kibana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch-kibana
    spec:
      containers:
        - image: nshou/elasticsearch-kibana
          name: elasticsearch-kibana
          ports:
            - containerPort: 9200
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
status: {}
