apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: humidity-processor
  name: humidity-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: humidity-processor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: humidity-processor
    spec:
      containers:
        - env:
            - name: input_topic
              value: weather-events
            - name: output_topic
              value: humidity-events
          image: humidity_processor_image
          name: humidity-processor
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
