apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: station10
  name: station10
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: station10
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: station10
    spec:
      containers:
        - env:
            - name: station_id
              value: "10"
            - name: topic_name
              value: weather-events
          image: weather_station_image
          name: station-10
          ports:
            - containerPort: 8092
          resources: {}
      restartPolicy: Always
status: {}
